# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift Playground
  pod 'Mixpanel-swift', :path => '/Users/joshwymer/mixpanel-swift/'

end

target 'NotificationServiceExtension' do
  use_frameworks!
  
  pod 'Mixpanel-swift', :path => '/Users/joshwymer/mixpanel-swift/'
end
