# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Playground
  #pod 'Mixpanel'
  pod 'Mixpanel', :path => '/Users/joshwymer/mixpanel-iphone/'
end

target 'NotificationServiceExtension' do
  use_frameworks!
  
  #pod 'Mixpanel'
  pod 'Mixpanel', :path => '/Users/joshwymer/mixpanel-iphone/'
end
